from __future__ import absolute_import, division, print_function, unicode_literals

from cosrlib.sources import Source


class MetadataSource(Source):
    """ Reads an intermediate dump of document metadata generated by
        --plugin plugins.dump.DocumentMetadata
    """

    already_parsed = True

    def get_documents(self, sqlc):

        fileformat = self.args.get("format") or "parquet"

        df = getattr(sqlc.read, fileformat)(self.args["path"])

        if int(self.args.get("maxdocs") or 0) > 0:
            df = df.limit(int(self.args["maxdocs"]))

        if self.args.get("fields"):
            df = df.select(self.args["fields"].split("+"))

        return df
